In [2]:
import numpy as np

arr = np.array([10,20,30,40,50])
arr[-5:-10]

array([10, 20, 30, 40])

In [7]:
data = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
arr = np.array(data)
arr[ : 2, :2]

array([[1, 2],
       [4, 5]])

In [9]:
notlar = np.array([85,92,78,90,88])

ort = np.mean(notlar)
print('Ortalama :',ort)

Ortalama : 86.6


In [10]:
enYuksekNot = np.max(notlar)
enDusukNot = np.min(notlar)

enYuksekNot

92

In [11]:
enDusukNot

78

In [15]:
# Şirketin aylık satış verileri(12 ay)

monthly_sales = np.array([1200,1500,1600,1700,1800,1900,2000,2100,2200,2300,2400,2500])

ilkaltıay = np.mean(monthly_sales[0:6])
ilkaltıay
print("ilk altı ay ortalaması :",ilkaltıay)

ilk altı ay ortalaması : 1616.6666666666667


In [18]:
sonaltıay = np.mean(monthly_sales[6,])
print("son altı ay ortalaması :",sonaltıay)

son altı ay ortalaması : 2000.0


In [40]:
daily_production = np.random.randint(100,200,size = 30)

toplam_uretim = np.sum(daily_production)
print('Toplam üretim: ',toplam_uretim)

Toplam üretim:  4526


In [41]:
ortalama_gunluk_uretim = np.mean(daily_production)
print('Ortalama günlük üretim: ',ortalama_gunluk_uretim)

Ortalama günlük üretim:  150.86666666666667


In [52]:
exam_scores = np.array([
    [85,90,88,92],
    [78,85,90,87],
    [92,88,82,95],
    [80,85,78,88]
])

ortalama = np.mean(exam_scores,axis = 1)
print(ortalama)

[88.75 85.   89.25 82.75]


In [53]:
uzaklık = exam_scores - ortalama[:,np.newaxis]
print(uzaklık)

[[-3.75  1.25 -0.75  3.25]
 [-7.    0.    5.    2.  ]
 [ 2.75 -1.25 -7.25  5.75]
 [-2.75  2.25 -4.75  5.25]]


In [54]:
temprature = np.array([22.5,23.0,23.5,24.0,24,5])
humidty = np.array([50,48,45,42,40])

sicaklik = np.mean(temprature)
print(sicaklik)

20.333333333333332


In [55]:
nem = np.mean(humidty)
print(nem)

45.0


In [56]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

A_transporse = A.T
print("transporse: ",A_transporse)

transporse:  [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [58]:
det_A = np.linalg.det(A)
print("Determinant :",det_A)

Determinant : -9.51619735392994e-16


In [63]:
import pandas as pd

df = pd.read_csv('student_scores.csv')

df

Hours  Scores
0     2.5      21
1     5.1      47
2     3.2      27
3     8.5      75
4     3.5      30
5     1.5      20
6     9.2      88
7     5.5      60
8     8.3      81
9     2.7      25
10    7.7      85
11    5.9      62
12    4.5      41
13    3.3      42
14    1.1      17
15    8.9      95
16    2.5      30
17    1.9      24
18    6.1      67
19    7.4      69
20    2.7      30
21    4.8      54
22    3.8      35
23    6.9      76
24    7.8      86

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Hours   25 non-null     float64
 1   Scores  25 non-null     int64  
dtypes: float64(1), int64(1)
memory usage: 532.0 bytes


In [65]:
print(df.describe())

           Hours     Scores
count  25.000000  25.000000
mean    5.012000  51.480000
std     2.525094  25.286887
min     1.100000  17.000000
25%     2.700000  30.000000
50%     4.800000  47.000000
75%     7.400000  75.000000
max     9.200000  95.000000


In [66]:
print(df.head())

   Hours  Scores
0    2.5      21
1    5.1      47
2    3.2      27
3    8.5      75
4    3.5      30


In [71]:
# Çalışan performans verileri
data = {
    'Employee': ['John', 'Anna', 'Peter', 'Linda', 'Mike'],
    'Department': ['HR', 'IT', 'HR', 'IT', 'HR'],
    'Performance': [8, 7, 9, 6, 8]
}

df = pd.DataFrame(data)
it_department = df[df["Department"] == 'IT']['Performance'].mean()
print(it_department)

6.5


In [73]:
dates = pd.date_range(start = '2023-01-01',periods = 365)
temprature = np.random.randint(low = -5,high = 30,size = 365)

df = pd.DataFrame({'Data': dates,"Temprature": temprature})

df

Data  Temprature
0   2023-01-01          11
1   2023-01-02           8
2   2023-01-03          15
3   2023-01-04          12
4   2023-01-05          27
..         ...         ...
360 2023-12-27          17
361 2023-12-28          11
362 2023-12-29          10
363 2023-12-30          15
364 2023-12-31          13

[365 rows x 2 columns]

In [81]:
ortalama_sicaklik = df['Temprature'].mean()
ortalama_sicaklik 

11.87945205479452

In [82]:
enYuksek = df['Temprature'].max()
enYuksek

29

In [83]:
enDusuk = df['Temprature'].min()
enDusuk

-5

In [94]:
# Şube günlük satış verileri
data = {
    'Branch': ['A', 'B', 'A', 'C', 'B', 'C'],
    'Date': ['2023-01-01', '2023-01-01', '2023-01-02', '2023-01-02', '2023-01-01', '2023-01-02'],
    'Sales': [1500, 2000, 1800, 2500, 2200, 1900]
}

df = pd.DataFrame(data)

ortalama_gunluk = df.groupby('Branch')['Sales'].mean()
print(ortalama_gunluk)

toplam_satıs_her_sube = df.groupby('Branch')['Sales'].sum()
print(toplam_satıs_her_sube)

Branch
A    1650.0
B    2100.0
C    2200.0
Name: Sales, dtype: float64
Branch
A    3300
B    4200
C    4400
Name: Sales, dtype: int64
