In [5]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arr1 = np.arange(100)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [7]:
arr2 = np.zeros(100)
arr2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
arr3 = np.ones(100)
arr3

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
arr4 = np.eye(50)
arr4

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [11]:
arr5 = np.linspace(0,100,5)
arr5

array([  0.,  25.,  50.,  75., 100.])

In [14]:
arr6 = np.random.randint(0,100)
arr6

11

In [21]:
arr7 = np.random.randint(0,100,1000)
arr7

array([ 4, 87, 86, 72, 11, 19, 80, 46, 99,  2, 90, 16, 48, 54, 47, 33, 47,
       79, 73,  9,  0, 50, 31, 13, 76, 32, 82, 69, 48, 50, 23, 39, 86, 41,
       23, 99, 41, 94, 48, 59, 22, 37, 88, 89,  6, 92, 57, 63, 28, 90, 53,
       38, 59, 11, 68, 70, 57, 58, 99, 65, 18, 17, 17, 31, 50, 69,  4, 70,
       78, 47,  7, 22, 46, 56, 73, 31, 81, 72, 45,  9, 49,  9, 38, 32, 69,
       47, 64, 74, 13, 18, 65, 25,  4, 16, 89,  9, 64, 66, 41, 73, 73, 20,
       86, 73, 50, 50, 24, 13, 77, 19, 54, 77, 61, 83, 89, 55, 23, 55, 88,
       54, 70, 46, 71,  2, 17, 30, 13, 47, 33, 66, 41, 71, 21, 84, 46, 67,
       33, 81, 56, 89, 71, 16, 71, 77, 13, 30, 83, 91, 46,  3, 26, 38, 99,
       29, 82,  3, 88,  4, 23, 31, 16,  1, 39, 45, 29,  9, 39, 99, 62, 41,
       38, 12,  3, 66, 30, 34, 21, 24, 53, 41, 22, 61, 97, 65, 81,  0, 62,
       55, 30, 55, 88, 12,  7, 57, 69, 76, 77,  6, 37,  1, 17, 43, 87, 65,
       61, 13, 59, 86,  3, 96, 42, 22, 76, 66, 56, 84, 84,  8, 58, 19,  6,
       69, 74, 37, 78,  1

In [22]:
np.random.rand(10)

array([0.73942304, 0.18940165, 0.68535976, 0.0682025 , 0.35323557,
       0.21522831, 0.48999837, 0.05526963, 0.27012657, 0.07686725])

In [24]:
arr8 = np.random.randn(5)
arr8
# -1 ve 1 arasında

array([-0.49821084, -0.09493484, -1.74957127, -2.28794911,  0.07113149])

In [32]:
arr9 = np.arange(1,251)
arr9

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [33]:
arr9.reshape(25,10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
       [111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
       [131, 132, 133, 134, 135, 136, 137, 138, 139, 140],
       [141, 142, 143, 144, 145, 146, 147, 148, 149, 150],
       [151, 152, 153, 154, 155, 156, 157, 158, 159, 160],
       [161, 162, 163, 164, 165, 166, 167, 168, 169, 170

In [34]:
arr9.min()

1

In [35]:
arr9.max()

250

In [36]:
arr7.min()

0

In [37]:
arr7.max()

99

In [38]:
# argmax() ve argmin() indekse göre bulur

In [40]:
# standart sapma
standart_sapma = np.std(arr7)
standart_sapma

28.721067511497548

In [41]:
arr1_orn  = np.arange(1,10)
arr1_orn

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
sıfırvebir = np.eye(10)
sıfırvebir

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [48]:
belirliaralik = np.linspace(0,10,2)
belirliaralik

array([ 0., 10.])

In [49]:
arangefonksiyonu = np.arange(0,10,2)
arangefonksiyonu

array([0, 2, 4, 6, 8])

In [50]:
arangefonksiyonu = np.arange(10,2)
arangefonksiyonu

array([], dtype=int32)

In [58]:
rastgele = np.random.randint(0,100,100)
rastgele1 = rastgele.reshape(10,10)
rastgele1

array([[ 8, 12, 67, 23, 89, 66,  8, 70,  7, 63],
       [92, 62,  0, 26,  1, 12, 35, 50, 41, 58],
       [30, 40, 17, 31, 23, 38, 97, 47, 91,  5],
       [22, 51, 55, 24, 43, 38, 85, 38,  9, 20],
       [74, 60, 88, 15,  9, 84, 15, 89, 21, 72],
       [38, 13, 87, 81, 11, 10, 94, 40, 73, 65],
       [91, 78, 44, 37, 82, 95, 25, 69, 68, 27],
       [24, 87, 46, 16, 84, 91, 34, 85, 54, 78],
       [91, 79, 23, 41, 44, 49, 75, 71, 76,  6],
       [27, 88, 76,  0, 70, 11, 28, 33, 11, 46]])

In [56]:
rastgele.reshape(10,10)

array([[22, 45, 41, 92, 23, 39, 18, 57, 87,  7],
       [95, 28, 70, 10, 67, 18, 54, 73, 28, 72],
       [79, 78, 93, 79, 37, 45, 37,  2, 22, 15],
       [ 3, 44,  1, 23, 70, 31, 66, 21, 31, 22],
       [75, 53, 19, 18, 98, 96, 63, 89, 50, 82],
       [36, 88, 31, 41,  6, 54, 82, 32, 90,  7],
       [82, 63, 48,  6, 54, 30, 72, 47, 66, 48],
       [60, 62, 31, 54, 30, 43,  8, 60,  3, 51],
       [78, 32, 96, 31, 33, 59, 93, 33, 35, 19],
       [92, 41,  0, 40, 94, 21, 14, 86, 27,  4]])

In [62]:
rastgele2 = np.random.randint(0,100,1000)
rastgele3 = np.random.randint(0,100,1000)

rastgeletoplam = rastgele2 + rastgele3
rastgeletoplam

array([ 21, 123,  91, 128,  77,  87, 133, 129, 123, 112,  84, 100, 184,
        82, 102, 123,  32,  88,  52,  59, 128, 103,  99, 138,  87,  83,
       183, 122,  95, 131,  59,  40, 119, 105, 113,  87,  49, 158,  55,
       115,  78, 134, 129,  64, 125, 168,  97,  73, 128,  83, 114, 163,
       133,  93, 138,  76,  99, 182, 112, 124, 112, 102, 136, 140, 101,
        82,  12,  89,  61, 107,  94, 122, 106,  18,  94, 109,  52,  66,
        76, 105, 100,  97,  34, 123,  95, 149,  77,  94, 105,  95, 179,
        31, 154,  81, 113, 109,  14,  76, 135, 150, 188, 137, 146,  62,
       108,  85,  58, 105,  46,  67,  69, 110, 139, 146, 103, 169,  69,
        81,  84,  95, 125, 144,  76, 152,  53,  90, 135, 103, 130,  93,
       132, 111, 114,  90,  57, 188,  88,  43,  31, 102, 124,  76, 129,
        64,  84, 180,  20,  45, 174,  95, 108,  95,  88, 129,  82, 188,
       127, 121,  10, 105, 160, 138,  97, 146, 102, 108, 127,  31,  53,
        49,  83, 157, 160, 167,  69,  88, 150, 103,  82,  29, 11

In [63]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
arr[2,2]

9

In [70]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [78]:
arr[::2]

array([0, 2, 4, 6, 8])

In [83]:
array = np.array([10,20,30,40,50])
print("ilk:",array.min(),"Son:", array.max())

ilk: 10 Son: 50


In [86]:
array[0:3]

array([10, 20, 30])

In [95]:
array[2:]

array([30, 40, 50])

In [97]:
array[::2]

array([10, 30, 50])

In [98]:
array[2::2]

array([30, 50])

In [116]:
veriler = np.array([[1,2,3],[4,5,6],[7,8,9]])

secilen_veriler = veriler[1:, 1:]

print(secilen_veriler)

[[5 6]
 [8 9]]


In [121]:
secilen_veriler2 = veriler[0:2,0:2]
print(secilen_veriler2)

[[1 2]
 [4 5]]


In [128]:
secilen_veriler3 = veriler[:,1]
secilen_veriler3

array([2, 5, 8])

In [135]:
secilen_veriler4 = veriler[1,:]
print(secilen_veriler4)

[4 5 6]
