In [1]:
import pandas as pd
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder


In [2]:
data = pd.read_csv("Data.csv")
cs = ColumnTransformer(transformers = [("encoder",OneHotEncoder(),[0])],remainder = "passthrough")
transferData = cs.fit_transform(data)
transferData
df = pd.DataFrame(transferData)
df

0    1    2     3        4    5
0  0.0  1.0  0.0  40.0  72000.0   No
1  0.0  0.0  1.0  27.0  48000.0  Yes
2  1.0  0.0  0.0  30.0  54000.0   No
3  0.0  0.0  1.0  38.0  61000.0   No
4  0.0  1.0  0.0  40.0      NaN  Yes
5  0.0  1.0  0.0  35.0  58000.0  Yes
6  1.0  0.0  0.0   NaN  52000.0   No
7  0.0  0.0  1.0  48.0  79000.0  Yes
8  0.0  1.0  0.0  50.0  83000.0   No
9  1.0  0.0  0.0  37.0  67000.0  Yes

In [3]:
data = {
    'Renkler': ['Kırmızı','Yeşil','Mavi','Kırmızı','Yeşil'],
    'Yaş': [25,32,47,51,62],
    'Maaş': [50000,60000,120000,80000,90000]
}

In [4]:
df = pd.DataFrame(data)
cs = ColumnTransformer(transformers = [("encoder",OneHotEncoder(),[0])],remainder = "passthrough")
transferData = cs.fit_transform(df)
transferData

array([[1.0e+00, 0.0e+00, 0.0e+00, 2.5e+01, 5.0e+04],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.2e+01, 6.0e+04],
       [0.0e+00, 1.0e+00, 0.0e+00, 4.7e+01, 1.2e+05],
       [1.0e+00, 0.0e+00, 0.0e+00, 5.1e+01, 8.0e+04],
       [0.0e+00, 0.0e+00, 1.0e+00, 6.2e+01, 9.0e+04]])

In [5]:
df2 = pd.DataFrame(transferData)
df2

0    1    2     3         4
0  1.0  0.0  0.0  25.0   50000.0
1  0.0  0.0  1.0  32.0   60000.0
2  0.0  1.0  0.0  47.0  120000.0
3  1.0  0.0  0.0  51.0   80000.0
4  0.0  0.0  1.0  62.0   90000.0

In [6]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

data = {
    'Renkler': ['Kırmızı','Yeşil','Mavi','Kırmızı','Yeşil']
}

df = pd.DataFrame(data)

yeni_data = le.fit_transform(df['Renkler'])

df = pd.DataFrame(yeni_data)
df

0
0  0
1  2
2  1
3  0
4  2

In [7]:
data = pd.read_csv("Data.csv")

df = pd.DataFrame(data)

le = LabelEncoder()

Y = df['Purchased']

yeni_data = le.fit_transform(Y)

df = pd.DataFrame(yeni_data)
df

0
0  0
1  1
2  0
3  0
4  1
5  1
6  0
7  1
8  0
9  1

In [8]:
from sklearn.model_selection import train_test_split

X = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])

y = np.array([0,1,0,1,0])

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2)
print(X_train,"train")

[[1 2]
 [3 4]
 [7 8]
 [5 6]] train


In [9]:
print(X_test)

[[ 9 10]]


In [10]:
data = pd.read_csv("Data.csv")

df = pd.DataFrame(data)

X = df.iloc[:,0:3]

Y = df['Purchased']

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2)
print(X_train)

  Country   Age   Salary
5  Turkey  35.0  58000.0
8  Turkey  50.0  83000.0
6   Japan   NaN  52000.0
9   Japan  37.0  67000.0
1     USA  27.0  48000.0
7     USA  48.0  79000.0
0  Turkey  40.0  72000.0
3     USA  38.0  61000.0


In [11]:
print(X_test)

  Country   Age   Salary
2   Japan  30.0  54000.0
4  Turkey  40.0      NaN


In [12]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
print(X_train)
print("*********************")
X_test[:,3:] =  ss.fit_transform(X_train[:,3:])
print(X_train)

  Country   Age   Salary
5  Turkey  35.0  58000.0
8  Turkey  50.0  83000.0
6   Japan   NaN  52000.0
9   Japan  37.0  67000.0
1     USA  27.0  48000.0
7     USA  48.0  79000.0
0  Turkey  40.0  72000.0
3     USA  38.0  61000.0
*********************


InvalidIndexError: (slice(None, None, None), slice(3, None, None))